name: CI
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.84.1
jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust ${{ env.RUST_VERSION }}
        run: rustup toolchain install ${{ env.RUST_VERSION }} --component clippy --component rustfmt && rustup default ${{ env.RUST_VERSION }}
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: Build
        run: cargo build --all
      - name: Run tests
        run: cargo test --all
      - name: Run clippy
        run: cargo clippy --all -- -D warnings
      - name: Run fmt
        run: cargo fmt --all -- --check
      - name: Build and Test wasm
        run: npm install && npm run build && npm test
      - name: Install license tool
        run: cargo install dd-rust-license-tool
      - name: Run license tool
        run: dd-rust-license-tool check
