name: release-please

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.87.0

permissions:
  id-token: write  # Required for OIDC
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created:  ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  npm-publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust ${{ env.RUST_VERSION }}
        run: rustup toolchain install ${{ env.RUST_VERSION }} --component clippy --component rustfmt && rustup default ${{ env.RUST_VERSION }}
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - run: npm install -g npm@latest
      - run: npm install && npm run build
      - run: npm publish --access public